#include <dirent.h>

/* Shared syscall/runtime helpers used by generated C and x64 native support C. */
static inline void iw_syscall_abort(const char *context) { fprintf(stderr, "Ironwall syscall failed in %s: %s\n", context, strerror(errno)); abort(); }
static inline void iw_syscall_abort_message(const char *context, const char *detail) { fprintf(stderr, "Ironwall syscall failed in %s: %s\n", context, detail); abort(); }
static inline char **iw_text_array_to_c_strings(iw_value_t raw_value, const char *context) { iw_array_value_t *array = iw_array_expect(raw_value, context); char **result = (char**)malloc(((size_t)array->length + 1u) * sizeof(char*)); if (result == NULL) { fprintf(stderr, "Ironwall allocation failed in %s\n", context); abort(); } for (int64_t index = 0; index < array->length; index += 1) { iw_text_value_t *value = iw_text_expect(array->items[index], context); result[index] = (char*)value->data; } result[array->length] = NULL; return result; }
static inline char **iw_text_array_to_exec_argv(iw_value_t raw_path, iw_value_t raw_argv, const char *context) { iw_text_value_t *path = iw_text_expect(raw_path, context); iw_array_value_t *array = iw_array_expect(raw_argv, context); char **result = (char**)malloc(((size_t)array->length + 2u) * sizeof(char*)); if (result == NULL) { fprintf(stderr, "Ironwall allocation failed in %s\n", context); abort(); } result[0] = (char*)path->data; for (int64_t index = 0; index < array->length; index += 1) { iw_text_value_t *value = iw_text_expect(array->items[index], context); result[index + 1] = (char*)value->data; } result[array->length + 1] = NULL; return result; }
static inline iw_value_t iw_make_i5_pair_array(int64_t left, int64_t right, const char *context) { iw_value_t result = iw_builtin_array_new(iw_from_i64(2), iw_from_i64(0)); iw_array_value_t *array = iw_array_expect(result, context); array->items[0] = iw_from_i64(left); array->items[1] = iw_from_i64(right); return result; }
static inline iw_value_t iw_make_epoll_event_array(const struct epoll_event *events, int64_t count, const char *context) { iw_value_t default_item = iw_make_i5_pair_array(0, 0, context); iw_value_t result = iw_builtin_array_new(iw_from_i64(count), default_item); iw_array_value_t *array = iw_array_expect(result, context); for (int64_t index = 0; index < count; index += 1) { array->items[index] = iw_make_i5_pair_array((int64_t)events[index].events, (int64_t)events[index].data.u64, context); } return result; }
static inline iw_value_t iw_make_i5_triple_array(int64_t first, int64_t second, int64_t third, const char *context) { iw_value_t result = iw_builtin_array_new(iw_from_i64(3), iw_from_i64(0)); iw_array_value_t *array = iw_array_expect(result, context); array->items[0] = iw_from_i64(first); array->items[1] = iw_from_i64(second); array->items[2] = iw_from_i64(third); return result; }
static inline iw_value_t iw_make_poll_event_array(const struct pollfd *fds, const int16_t *events, nfds_t count, const char *context) { int64_t ready_count = 0; for (nfds_t index = 0; index < count; index += 1u) { if (fds[index].revents != 0) { ready_count += 1; } } iw_value_t result = iw_builtin_array_new(iw_from_i64(ready_count), iw_make_i5_triple_array(0, 0, 0, context)); iw_array_value_t *array = iw_array_expect(result, context); int64_t ready_index = 0; for (nfds_t index = 0; index < count; index += 1u) { if (fds[index].revents != 0) { array->items[ready_index] = iw_make_i5_triple_array((int64_t)fds[index].fd, (int64_t)events[index], (int64_t)fds[index].revents, context); ready_index += 1; } } return result; }
static inline iw_value_t iw_make_signalfd_info_array(int64_t signo, int64_t pid, int64_t uid, int64_t status, const char *context) { iw_value_t result = iw_builtin_array_new(iw_from_i64(4), iw_from_i64(0)); iw_array_value_t *array = iw_array_expect(result, context); array->items[0] = iw_from_i64(signo); array->items[1] = iw_from_i64(pid); array->items[2] = iw_from_i64(uid); array->items[3] = iw_from_i64(status); return result; }
static inline iw_value_t iw_make_i5_stat_array(int64_t device, int64_t inode, int64_t mode, int64_t link_count, int64_t uid, int64_t gid, int64_t rdevice, int64_t size, int64_t block_size, int64_t block_count, int64_t atime_sec, int64_t mtime_sec, int64_t ctime_sec, const char *context) { iw_value_t result = iw_builtin_array_new(iw_from_i64(13), iw_from_i64(0)); iw_array_value_t *array = iw_array_expect(result, context); array->items[0] = iw_from_i64(device); array->items[1] = iw_from_i64(inode); array->items[2] = iw_from_i64(mode); array->items[3] = iw_from_i64(link_count); array->items[4] = iw_from_i64(uid); array->items[5] = iw_from_i64(gid); array->items[6] = iw_from_i64(rdevice); array->items[7] = iw_from_i64(size); array->items[8] = iw_from_i64(block_size); array->items[9] = iw_from_i64(block_count); array->items[10] = iw_from_i64(atime_sec); array->items[11] = iw_from_i64(mtime_sec); array->items[12] = iw_from_i64(ctime_sec); return result; }
static inline char *iw_load_proc_cmdline(size_t *out_length, const char *context) { FILE *file = fopen("/proc/self/cmdline", "rb"); size_t capacity = 256u; size_t length = 0u; char *buffer; if (file == NULL) { iw_syscall_abort(context); } buffer = (char*)malloc(capacity); if (buffer == NULL) { fclose(file); fprintf(stderr, "Ironwall allocation failed in %s\n", context); abort(); } for (;;) { size_t available = capacity - length; size_t count; if (available == 0u) { capacity *= 2u; buffer = (char*)realloc(buffer, capacity); if (buffer == NULL) { fclose(file); fprintf(stderr, "Ironwall allocation failed in %s\n", context); abort(); } available = capacity - length; } count = fread(buffer + length, 1u, available, file); length += count; if (count < available) { if (ferror(file)) { free(buffer); fclose(file); iw_syscall_abort(context); } break; } } fclose(file); *out_length = length; return buffer; }
static inline iw_value_t iw_make_i5_process_array(int64_t pid, const char *context) { iw_value_t result = iw_builtin_array_new(iw_from_i64(3), iw_from_i64(0)); iw_array_value_t *array = iw_array_expect(result, context); array->items[0] = iw_from_i64(pid); array->items[1] = iw_from_i64(0); array->items[2] = iw_from_i64(pid); return result; }
static inline iw_value_t iw_builtin_sys_fd_open_read_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_fd_open_read_s3 path"); int fd = open(path->data, O_RDONLY); if (fd < 0) { iw_syscall_abort("sys_fd_open_read_s3"); } return iw_from_i64(fd); }
static inline iw_value_t iw_builtin_sys_fd_open_write_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_fd_open_write_s3 path"); int fd = open(path->data, O_WRONLY | O_CREAT | O_TRUNC, 0666); if (fd < 0) { iw_syscall_abort("sys_fd_open_write_s3"); } return iw_from_i64(fd); }
static inline iw_value_t iw_builtin_sys_fd_open_append_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_fd_open_append_s3 path"); int fd = open(path->data, O_WRONLY | O_CREAT | O_APPEND, 0666); if (fd < 0) { iw_syscall_abort("sys_fd_open_append_s3"); } return iw_from_i64(fd); }
static inline iw_value_t iw_builtin_sys_fd_openat_read_s3(iw_value_t raw_dir_fd, iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_fd_openat_read_s3 path"); int fd = openat((int)iw_as_i64(raw_dir_fd), path->data, O_RDONLY); if (fd < 0) { iw_syscall_abort("sys_fd_openat_read_s3"); } return iw_from_i64(fd); }
static inline iw_value_t iw_builtin_sys_fd_openat_write_s3(iw_value_t raw_dir_fd, iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_fd_openat_write_s3 path"); int fd = openat((int)iw_as_i64(raw_dir_fd), path->data, O_WRONLY | O_CREAT | O_TRUNC, 0666); if (fd < 0) { iw_syscall_abort("sys_fd_openat_write_s3"); } return iw_from_i64(fd); }
static inline iw_value_t iw_builtin_sys_fd_creat_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_fd_creat_s3 path"); int fd = creat(path->data, 0666); if (fd < 0) { iw_syscall_abort("sys_fd_creat_s3"); } return iw_from_i64(fd); }
static inline iw_value_t iw_builtin_sys_fd_close(iw_value_t raw_fd) { if (close((int)iw_as_i64(raw_fd)) < 0) { iw_syscall_abort("sys_fd_close"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_fd_read_s3(iw_value_t raw_fd, iw_value_t raw_size) { int64_t size = iw_as_i64(raw_size); if (size < 0) { fprintf(stderr, "Ironwall sys_fd_read_s3 size must be non-negative: %lld\n", (long long)size); abort(); } if (size == 0) { return iw_text_copy_bytes("", 0u, "sys_fd_read_s3"); } char *buffer = (char*)malloc((size_t)size); if (buffer == NULL) { fprintf(stderr, "Ironwall allocation failed in sys_fd_read_s3\n"); abort(); } ssize_t count = read((int)iw_as_i64(raw_fd), buffer, (size_t)size); if (count < 0) { free(buffer); iw_syscall_abort("sys_fd_read_s3"); } iw_value_t result = iw_text_copy_bytes(buffer, (size_t)count, "sys_fd_read_s3"); free(buffer); return result; }
static inline iw_value_t iw_builtin_sys_fd_write_s3(iw_value_t raw_fd, iw_value_t raw_value) { iw_text_value_t *value = iw_text_expect(raw_value, "sys_fd_write_s3 value"); size_t written = 0u; while (written < value->length) { ssize_t chunk = write((int)iw_as_i64(raw_fd), value->data + written, (size_t)value->length - written); if (chunk < 0) { iw_syscall_abort("sys_fd_write_s3"); } if (chunk == 0) { fprintf(stderr, "Ironwall short write in sys_fd_write_s3\n"); abort(); } written += (size_t)chunk; } return iw_from_i64((int64_t)written); }
static inline iw_value_t iw_builtin_sys_fd_pread_s3(iw_value_t raw_fd, iw_value_t raw_size, iw_value_t raw_offset) { int64_t size = iw_as_i64(raw_size); if (size < 0) { fprintf(stderr, "Ironwall sys_fd_pread_s3 size must be non-negative: %lld\n", (long long)size); abort(); } if (size == 0) { return iw_text_copy_bytes("", 0u, "sys_fd_pread_s3"); } char *buffer = (char*)malloc((size_t)size); if (buffer == NULL) { fprintf(stderr, "Ironwall allocation failed in sys_fd_pread_s3\n"); abort(); } ssize_t count = pread((int)iw_as_i64(raw_fd), buffer, (size_t)size, (off_t)iw_as_i64(raw_offset)); if (count < 0) { free(buffer); iw_syscall_abort("sys_fd_pread_s3"); } iw_value_t result = iw_text_copy_bytes(buffer, (size_t)count, "sys_fd_pread_s3"); free(buffer); return result; }
static inline iw_value_t iw_builtin_sys_fd_pwrite_s3(iw_value_t raw_fd, iw_value_t raw_value, iw_value_t raw_offset) { iw_text_value_t *value = iw_text_expect(raw_value, "sys_fd_pwrite_s3 value"); size_t written = 0u; int64_t base_offset = iw_as_i64(raw_offset); while (written < value->length) { ssize_t chunk = pwrite((int)iw_as_i64(raw_fd), value->data + written, (size_t)value->length - written, (off_t)(base_offset + (int64_t)written)); if (chunk < 0) { iw_syscall_abort("sys_fd_pwrite_s3"); } if (chunk == 0) { fprintf(stderr, "Ironwall short write in sys_fd_pwrite_s3\n"); abort(); } written += (size_t)chunk; } return iw_from_i64((int64_t)written); }
static inline iw_value_t iw_builtin_sys_fd_readv_s3(iw_value_t raw_fd, iw_value_t raw_sizes) { iw_array_value_t *sizes = iw_array_expect(raw_sizes, "sys_fd_readv_s3 sizes"); size_t vector_count = (size_t)sizes->length; struct iovec *iovecs = vector_count == 0u ? NULL : (struct iovec*)calloc(vector_count, sizeof(struct iovec)); char **buffers = vector_count == 0u ? NULL : (char**)calloc(vector_count, sizeof(char*)); size_t *buffer_sizes = vector_count == 0u ? NULL : (size_t*)calloc(vector_count, sizeof(size_t)); if ((vector_count != 0u) && (iovecs == NULL || buffers == NULL || buffer_sizes == NULL)) { free(iovecs); free(buffers); free(buffer_sizes); fprintf(stderr, "Ironwall allocation failed in sys_fd_readv_s3\n"); abort(); } for (int64_t index = 0; index < sizes->length; index += 1) { int64_t part_size = iw_as_i64(sizes->items[index]); if (part_size < 0) { free(iovecs); free(buffers); free(buffer_sizes); fprintf(stderr, "Ironwall sys_fd_readv_s3 size must be non-negative: %lld\n", (long long)part_size); abort(); } buffer_sizes[index] = (size_t)part_size; if (part_size > 0) { buffers[index] = (char*)malloc((size_t)part_size); if (buffers[index] == NULL) { for (int64_t cleanup = 0; cleanup < index; cleanup += 1) { free(buffers[cleanup]); } free(iovecs); free(buffers); free(buffer_sizes); fprintf(stderr, "Ironwall allocation failed in sys_fd_readv_s3\n"); abort(); } iovecs[index].iov_base = buffers[index]; iovecs[index].iov_len = (size_t)part_size; } } ssize_t count = readv((int)iw_as_i64(raw_fd), iovecs, (int)vector_count); if (count < 0) { for (size_t index = 0; index < vector_count; index += 1) { free(buffers[index]); } free(iovecs); free(buffers); free(buffer_sizes); iw_syscall_abort("sys_fd_readv_s3"); } iw_value_t result = iw_builtin_array_new(iw_from_i64(sizes->length), iw_text_copy_bytes("", 0u, "sys_fd_readv_s3 default")); iw_array_value_t *result_array = iw_array_expect(result, "sys_fd_readv_s3 result"); ssize_t remaining = count; for (int64_t index = 0; index < sizes->length; index += 1) { size_t chunk_size = buffer_sizes[index]; size_t actual_size = 0u; if (remaining > 0) { actual_size = (size_t)remaining < chunk_size ? (size_t)remaining : chunk_size; remaining -= (ssize_t)actual_size; } result_array->items[index] = iw_text_copy_bytes(chunk_size == 0u ? "" : buffers[index], actual_size, "sys_fd_readv_s3 item"); free(buffers[index]); } free(iovecs); free(buffers); free(buffer_sizes); return result; }
static inline iw_value_t iw_builtin_sys_fd_writev_s3(iw_value_t raw_fd, iw_value_t raw_chunks) { iw_array_value_t *chunks = iw_array_expect(raw_chunks, "sys_fd_writev_s3 chunks"); size_t vector_count = (size_t)chunks->length; iw_text_value_t **texts = vector_count == 0u ? NULL : (iw_text_value_t**)calloc(vector_count, sizeof(iw_text_value_t*)); size_t *offsets = vector_count == 0u ? NULL : (size_t*)calloc(vector_count, sizeof(size_t)); if ((vector_count != 0u) && (texts == NULL || offsets == NULL)) { free(texts); free(offsets); fprintf(stderr, "Ironwall allocation failed in sys_fd_writev_s3\n"); abort(); } for (int64_t index = 0; index < chunks->length; index += 1) { texts[index] = iw_text_expect(chunks->items[index], "sys_fd_writev_s3 item"); } size_t completed = 0u; while (completed < vector_count && texts[completed]->length == 0u) { completed += 1u; } size_t total_written = 0u; while (completed < vector_count) { size_t active_count = vector_count - completed; struct iovec *iovecs = (struct iovec*)calloc(active_count, sizeof(struct iovec)); if (iovecs == NULL) { free(texts); free(offsets); fprintf(stderr, "Ironwall allocation failed in sys_fd_writev_s3\n"); abort(); } for (size_t local_index = 0u; local_index < active_count; local_index += 1u) { size_t source_index = completed + local_index; iovecs[local_index].iov_base = (void*)(texts[source_index]->data + offsets[source_index]); iovecs[local_index].iov_len = (size_t)texts[source_index]->length - offsets[source_index]; } ssize_t chunk = writev((int)iw_as_i64(raw_fd), iovecs, (int)active_count); free(iovecs); if (chunk < 0) { free(texts); free(offsets); iw_syscall_abort("sys_fd_writev_s3"); } if (chunk == 0) { free(texts); free(offsets); fprintf(stderr, "Ironwall short write in sys_fd_writev_s3\n"); abort(); } total_written += (size_t)chunk; size_t remaining_chunk = (size_t)chunk; while (completed < vector_count && remaining_chunk > 0u) { size_t current_remaining = (size_t)texts[completed]->length - offsets[completed]; if (remaining_chunk < current_remaining) { offsets[completed] += remaining_chunk; remaining_chunk = 0u; } else { remaining_chunk -= current_remaining; offsets[completed] = (size_t)texts[completed]->length; completed += 1u; while (completed < vector_count && texts[completed]->length == 0u) { completed += 1u; } } } } free(texts); free(offsets); return iw_from_i64((int64_t)total_written); }
static inline iw_value_t iw_builtin_sys_fd_sendfile(iw_value_t raw_out_fd, iw_value_t raw_in_fd, iw_value_t raw_count) { int64_t count = iw_as_i64(raw_count); if (count < 0) { fprintf(stderr, "Ironwall sys_fd_sendfile count must be non-negative: %lld\n", (long long)count); abort(); } ssize_t written = sendfile((int)iw_as_i64(raw_out_fd), (int)iw_as_i64(raw_in_fd), NULL, (size_t)count); if (written < 0) { iw_syscall_abort("sys_fd_sendfile"); } return iw_from_i64((int64_t)written); }
static inline iw_value_t iw_builtin_sys_fd_lseek(iw_value_t raw_fd, iw_value_t raw_offset, iw_value_t raw_whence) { off_t result = lseek((int)iw_as_i64(raw_fd), (off_t)iw_as_i64(raw_offset), (int)iw_as_i64(raw_whence)); if (result < 0) { iw_syscall_abort("sys_fd_lseek"); } return iw_from_i64((int64_t)result); }
static inline iw_value_t iw_builtin_sys_fd_fsync(iw_value_t raw_fd) { if (fsync((int)iw_as_i64(raw_fd)) < 0) { iw_syscall_abort("sys_fd_fsync"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_fd_fdatasync(iw_value_t raw_fd) { if (fdatasync((int)iw_as_i64(raw_fd)) < 0) { iw_syscall_abort("sys_fd_fdatasync"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_fd_fstat(iw_value_t raw_fd) { struct stat stat_value; if (fstat((int)iw_as_i64(raw_fd), &stat_value) < 0) { iw_syscall_abort("sys_fd_fstat"); } return iw_make_i5_stat_array((int64_t)stat_value.st_dev, (int64_t)stat_value.st_ino, (int64_t)stat_value.st_mode, (int64_t)stat_value.st_nlink, (int64_t)stat_value.st_uid, (int64_t)stat_value.st_gid, (int64_t)stat_value.st_rdev, (int64_t)stat_value.st_size, (int64_t)stat_value.st_blksize, (int64_t)stat_value.st_blocks, (int64_t)stat_value.st_atime, (int64_t)stat_value.st_mtime, (int64_t)stat_value.st_ctime, "sys_fd_fstat"); }
static inline iw_value_t iw_builtin_sys_fd_dup(iw_value_t raw_fd) { int result = dup((int)iw_as_i64(raw_fd)); if (result < 0) { iw_syscall_abort("sys_fd_dup"); } return iw_from_i64(result); }
static inline iw_value_t iw_builtin_sys_fd_dup2(iw_value_t raw_source_fd, iw_value_t raw_target_fd) { int result = dup2((int)iw_as_i64(raw_source_fd), (int)iw_as_i64(raw_target_fd)); if (result < 0) { iw_syscall_abort("sys_fd_dup2"); } return iw_from_i64(result); }
static inline iw_value_t iw_builtin_sys_fd_dup3(iw_value_t raw_source_fd, iw_value_t raw_target_fd, iw_value_t raw_flags) { long result = syscall(SYS_dup3, (long)iw_as_i64(raw_source_fd), (long)iw_as_i64(raw_target_fd), (long)iw_as_i64(raw_flags)); if (result < 0) { iw_syscall_abort("sys_fd_dup3"); } return iw_from_i64((int64_t)result); }
static inline iw_value_t iw_builtin_sys_fd_fcntl(iw_value_t raw_fd, iw_value_t raw_cmd, iw_value_t raw_arg) { int result = fcntl((int)iw_as_i64(raw_fd), (int)iw_as_i64(raw_cmd), (int)iw_as_i64(raw_arg)); if (result < 0) { iw_syscall_abort("sys_fd_fcntl"); } return iw_from_i64((int64_t)result); }
static inline iw_value_t iw_builtin_sys_fd_pipe2(void) { int fds[2] = { -1, -1 }; if (pipe(fds) < 0) { iw_syscall_abort("sys_fd_pipe2"); } return iw_make_i5_pair_array((int64_t)fds[0], (int64_t)fds[1], "sys_fd_pipe2"); }
static inline iw_value_t iw_builtin_sys_net_socket_tcp4(void) { int fd = socket(AF_INET, SOCK_STREAM, 0); if (fd < 0) { iw_syscall_abort("sys_net_socket_tcp4"); } return iw_from_i64((int64_t)fd); }
static inline iw_value_t iw_builtin_sys_net_setsockopt_reuseaddr(iw_value_t raw_fd) { int enabled = 1; if (setsockopt((int)iw_as_i64(raw_fd), SOL_SOCKET, SO_REUSEADDR, &enabled, (socklen_t)sizeof(enabled)) < 0) { iw_syscall_abort("sys_net_setsockopt_reuseaddr"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_setsockopt_reuseport(iw_value_t raw_fd) { int enabled = 1; if (setsockopt((int)iw_as_i64(raw_fd), SOL_SOCKET, SO_REUSEPORT, &enabled, (socklen_t)sizeof(enabled)) < 0) { iw_syscall_abort("sys_net_setsockopt_reuseport"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_setsockopt_tcp_nodelay(iw_value_t raw_fd) { int enabled = 1; if (setsockopt((int)iw_as_i64(raw_fd), IPPROTO_TCP, TCP_NODELAY, &enabled, (socklen_t)sizeof(enabled)) < 0) { iw_syscall_abort("sys_net_setsockopt_tcp_nodelay"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_getsockopt_error(iw_value_t raw_fd) { int error_value = 0; socklen_t error_length = (socklen_t)sizeof(error_value); if (getsockopt((int)iw_as_i64(raw_fd), SOL_SOCKET, SO_ERROR, &error_value, &error_length) < 0) { iw_syscall_abort("sys_net_getsockopt_error"); } return iw_from_i64((int64_t)error_value); }
static inline iw_value_t iw_builtin_sys_net_bind_ipv4_any(iw_value_t raw_fd, iw_value_t raw_port) { struct sockaddr_in address; memset(&address, 0, sizeof(address)); address.sin_family = AF_INET; address.sin_port = htons((uint16_t)iw_as_i64(raw_port)); address.sin_addr.s_addr = htonl(INADDR_ANY); if (bind((int)iw_as_i64(raw_fd), (struct sockaddr*)&address, (socklen_t)sizeof(address)) < 0) { iw_syscall_abort("sys_net_bind_ipv4_any"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_bind_ipv4_loopback(iw_value_t raw_fd, iw_value_t raw_port) { struct sockaddr_in address; memset(&address, 0, sizeof(address)); address.sin_family = AF_INET; address.sin_port = htons((uint16_t)iw_as_i64(raw_port)); address.sin_addr.s_addr = htonl(INADDR_LOOPBACK); if (bind((int)iw_as_i64(raw_fd), (struct sockaddr*)&address, (socklen_t)sizeof(address)) < 0) { iw_syscall_abort("sys_net_bind_ipv4_loopback"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_getsockname_ipv4_port(iw_value_t raw_fd) { struct sockaddr_in address; socklen_t address_length = (socklen_t)sizeof(address); memset(&address, 0, sizeof(address)); if (getsockname((int)iw_as_i64(raw_fd), (struct sockaddr*)&address, &address_length) < 0) { iw_syscall_abort("sys_net_getsockname_ipv4_port"); } return iw_from_i64((int64_t)ntohs(address.sin_port)); }
static inline iw_value_t iw_builtin_sys_net_listen(iw_value_t raw_fd, iw_value_t raw_backlog) { if (listen((int)iw_as_i64(raw_fd), (int)iw_as_i64(raw_backlog)) < 0) { iw_syscall_abort("sys_net_listen"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_accept(iw_value_t raw_fd) { int accepted_fd = accept((int)iw_as_i64(raw_fd), NULL, NULL); if (accepted_fd < 0) { iw_syscall_abort("sys_net_accept"); } return iw_from_i64((int64_t)accepted_fd); }
static inline iw_value_t iw_builtin_sys_net_accept4(iw_value_t raw_fd, iw_value_t raw_flags) { int accepted_fd = accept4((int)iw_as_i64(raw_fd), NULL, NULL, (int)iw_as_i64(raw_flags)); if (accepted_fd < 0) { iw_syscall_abort("sys_net_accept4"); } return iw_from_i64((int64_t)accepted_fd); }
static inline iw_value_t iw_builtin_sys_net_socketpair_stream(void) { int fds[2] = { -1, -1 }; if (socketpair(AF_UNIX, SOCK_STREAM, 0, fds) < 0) { iw_syscall_abort("sys_net_socketpair_stream"); } return iw_make_i5_pair_array((int64_t)fds[0], (int64_t)fds[1], "sys_net_socketpair_stream"); }
static inline iw_value_t iw_builtin_sys_net_connect_ipv4_loopback(iw_value_t raw_fd, iw_value_t raw_port) { struct sockaddr_in address; memset(&address, 0, sizeof(address)); address.sin_family = AF_INET; address.sin_port = htons((uint16_t)iw_as_i64(raw_port)); address.sin_addr.s_addr = htonl(INADDR_LOOPBACK); if (connect((int)iw_as_i64(raw_fd), (struct sockaddr*)&address, (socklen_t)sizeof(address)) < 0) { iw_syscall_abort("sys_net_connect_ipv4_loopback"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_net_send_s3(iw_value_t raw_fd, iw_value_t raw_value) { iw_text_value_t *value = iw_text_expect(raw_value, "sys_net_send_s3 value"); size_t written = 0u; while (written < value->length) { ssize_t chunk = send((int)iw_as_i64(raw_fd), value->data + written, (size_t)value->length - written, 0); if (chunk < 0) { iw_syscall_abort("sys_net_send_s3"); } if (chunk == 0) { fprintf(stderr, "Ironwall short send in sys_net_send_s3\n"); abort(); } written += (size_t)chunk; } return iw_from_i64((int64_t)written); }
static inline iw_value_t iw_builtin_sys_net_recv_s3(iw_value_t raw_fd, iw_value_t raw_size) { int64_t size = iw_as_i64(raw_size); if (size < 0) { fprintf(stderr, "Ironwall sys_net_recv_s3 size must be non-negative: %lld\n", (long long)size); abort(); } if (size == 0) { return iw_text_copy_bytes("", 0u, "sys_net_recv_s3"); } char *buffer = (char*)malloc((size_t)size); if (buffer == NULL) { fprintf(stderr, "Ironwall allocation failed in sys_net_recv_s3\n"); abort(); } ssize_t count = recv((int)iw_as_i64(raw_fd), buffer, (size_t)size, 0); if (count < 0) { free(buffer); iw_syscall_abort("sys_net_recv_s3"); } iw_value_t result = iw_text_copy_bytes(buffer, (size_t)count, "sys_net_recv_s3"); free(buffer); return result; }
static inline iw_value_t iw_builtin_sys_net_sendmsg_s3(iw_value_t raw_fd, iw_value_t raw_chunks, iw_value_t raw_flags) { iw_array_value_t *chunks = iw_array_expect(raw_chunks, "sys_net_sendmsg_s3 chunks"); size_t vector_count = (size_t)chunks->length; iw_text_value_t **texts = vector_count == 0u ? NULL : (iw_text_value_t**)calloc(vector_count, sizeof(iw_text_value_t*)); size_t *offsets = vector_count == 0u ? NULL : (size_t*)calloc(vector_count, sizeof(size_t)); if ((vector_count != 0u) && (texts == NULL || offsets == NULL)) { free(texts); free(offsets); fprintf(stderr, "Ironwall allocation failed in sys_net_sendmsg_s3\n"); abort(); } for (int64_t index = 0; index < chunks->length; index += 1) { texts[index] = iw_text_expect(chunks->items[index], "sys_net_sendmsg_s3 item"); } size_t completed = 0u; while (completed < vector_count && texts[completed]->length == 0u) { completed += 1u; } size_t total_written = 0u; while (completed < vector_count) { size_t active_count = vector_count - completed; struct iovec *iovecs = (struct iovec*)calloc(active_count, sizeof(struct iovec)); struct msghdr message; if (iovecs == NULL) { free(texts); free(offsets); fprintf(stderr, "Ironwall allocation failed in sys_net_sendmsg_s3\n"); abort(); } memset(&message, 0, sizeof(message)); for (size_t local_index = 0u; local_index < active_count; local_index += 1u) { size_t source_index = completed + local_index; iovecs[local_index].iov_base = (void*)(texts[source_index]->data + offsets[source_index]); iovecs[local_index].iov_len = (size_t)texts[source_index]->length - offsets[source_index]; } message.msg_iov = iovecs; message.msg_iovlen = active_count; ssize_t chunk = sendmsg((int)iw_as_i64(raw_fd), &message, (int)iw_as_i64(raw_flags)); free(iovecs); if (chunk < 0) { free(texts); free(offsets); iw_syscall_abort("sys_net_sendmsg_s3"); } if (chunk == 0) { free(texts); free(offsets); fprintf(stderr, "Ironwall short send in sys_net_sendmsg_s3\n"); abort(); } total_written += (size_t)chunk; size_t remaining_chunk = (size_t)chunk; while (completed < vector_count && remaining_chunk > 0u) { size_t current_remaining = (size_t)texts[completed]->length - offsets[completed]; if (remaining_chunk < current_remaining) { offsets[completed] += remaining_chunk; remaining_chunk = 0u; } else { remaining_chunk -= current_remaining; offsets[completed] = (size_t)texts[completed]->length; completed += 1u; while (completed < vector_count && texts[completed]->length == 0u) { completed += 1u; } } } } free(texts); free(offsets); return iw_from_i64((int64_t)total_written); }
static inline iw_value_t iw_builtin_sys_net_recvmsg_s3(iw_value_t raw_fd, iw_value_t raw_sizes, iw_value_t raw_flags) { iw_array_value_t *sizes = iw_array_expect(raw_sizes, "sys_net_recvmsg_s3 sizes"); size_t vector_count = (size_t)sizes->length; struct iovec *iovecs = vector_count == 0u ? NULL : (struct iovec*)calloc(vector_count, sizeof(struct iovec)); char **buffers = vector_count == 0u ? NULL : (char**)calloc(vector_count, sizeof(char*)); size_t *buffer_sizes = vector_count == 0u ? NULL : (size_t*)calloc(vector_count, sizeof(size_t)); if ((vector_count != 0u) && (iovecs == NULL || buffers == NULL || buffer_sizes == NULL)) { free(iovecs); free(buffers); free(buffer_sizes); fprintf(stderr, "Ironwall allocation failed in sys_net_recvmsg_s3\n"); abort(); } for (int64_t index = 0; index < sizes->length; index += 1) { int64_t part_size = iw_as_i64(sizes->items[index]); if (part_size < 0) { free(iovecs); free(buffers); free(buffer_sizes); fprintf(stderr, "Ironwall sys_net_recvmsg_s3 size must be non-negative: %lld\n", (long long)part_size); abort(); } buffer_sizes[index] = (size_t)part_size; if (part_size > 0) { buffers[index] = (char*)malloc((size_t)part_size); if (buffers[index] == NULL) { for (int64_t cleanup = 0; cleanup < index; cleanup += 1) { free(buffers[cleanup]); } free(iovecs); free(buffers); free(buffer_sizes); fprintf(stderr, "Ironwall allocation failed in sys_net_recvmsg_s3\n"); abort(); } iovecs[index].iov_base = buffers[index]; iovecs[index].iov_len = (size_t)part_size; } } struct msghdr message; memset(&message, 0, sizeof(message)); message.msg_iov = iovecs; message.msg_iovlen = vector_count; ssize_t count = recvmsg((int)iw_as_i64(raw_fd), &message, (int)iw_as_i64(raw_flags)); if (count < 0) { for (size_t index = 0; index < vector_count; index += 1) { free(buffers[index]); } free(iovecs); free(buffers); free(buffer_sizes); iw_syscall_abort("sys_net_recvmsg_s3"); } iw_value_t result = iw_builtin_array_new(iw_from_i64(sizes->length), iw_text_copy_bytes("", 0u, "sys_net_recvmsg_s3 default")); iw_array_value_t *result_array = iw_array_expect(result, "sys_net_recvmsg_s3 result"); ssize_t remaining = count; for (int64_t index = 0; index < sizes->length; index += 1) { size_t chunk_size = buffer_sizes[index]; size_t actual_size = 0u; if (remaining > 0) { actual_size = (size_t)remaining < chunk_size ? (size_t)remaining : chunk_size; remaining -= (ssize_t)actual_size; } result_array->items[index] = iw_text_copy_bytes(chunk_size == 0u ? "" : buffers[index], actual_size, "sys_net_recvmsg_s3 item"); free(buffers[index]); } free(iovecs); free(buffers); free(buffer_sizes); return result; }
static inline iw_value_t iw_builtin_sys_net_shutdown(iw_value_t raw_fd, iw_value_t raw_how) { if (shutdown((int)iw_as_i64(raw_fd), (int)iw_as_i64(raw_how)) < 0) { iw_syscall_abort("sys_net_shutdown"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_epoll_create(void) { int epoll_fd = epoll_create1(0); if (epoll_fd < 0) { iw_syscall_abort("sys_epoll_create"); } return iw_from_i64((int64_t)epoll_fd); }
static inline iw_value_t iw_builtin_sys_epoll_ctl(iw_value_t raw_epoll_fd, iw_value_t raw_op, iw_value_t raw_fd, iw_value_t raw_events, iw_value_t raw_data) { struct epoll_event event; memset(&event, 0, sizeof(event)); event.events = (uint32_t)iw_as_i64(raw_events); event.data.u64 = (uint64_t)iw_as_i64(raw_data); if (epoll_ctl((int)iw_as_i64(raw_epoll_fd), (int)iw_as_i64(raw_op), (int)iw_as_i64(raw_fd), (iw_as_i64(raw_op) == EPOLL_CTL_DEL) ? NULL : &event) < 0) { iw_syscall_abort("sys_epoll_ctl"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_epoll_wait(iw_value_t raw_epoll_fd, iw_value_t raw_max_events, iw_value_t raw_timeout_ms) { int64_t max_events = iw_as_i64(raw_max_events); if (max_events < 0) { fprintf(stderr, "Ironwall sys_epoll_wait max_events must be non-negative: %lld\n", (long long)max_events); abort(); } if (max_events == 0) { return iw_builtin_array_new(iw_from_i64(0), iw_from_i64(0)); } struct epoll_event *events = (struct epoll_event*)calloc((size_t)max_events, sizeof(struct epoll_event)); if (events == NULL) { fprintf(stderr, "Ironwall allocation failed in sys_epoll_wait\n"); abort(); } int ready_count = epoll_wait((int)iw_as_i64(raw_epoll_fd), events, (int)max_events, (int)iw_as_i64(raw_timeout_ms)); if (ready_count < 0) { free(events); iw_syscall_abort("sys_epoll_wait"); } iw_value_t result = iw_make_epoll_event_array(events, (int64_t)ready_count, "sys_epoll_wait"); free(events); return result; }
static inline iw_value_t iw_builtin_sys_epoll_pwait(iw_value_t raw_epoll_fd, iw_value_t raw_max_events, iw_value_t raw_timeout_ms) { int64_t max_events = iw_as_i64(raw_max_events); if (max_events < 0) { fprintf(stderr, "Ironwall sys_epoll_pwait max_events must be non-negative: %lld\n", (long long)max_events); abort(); } if (max_events == 0) { return iw_builtin_array_new(iw_from_i64(0), iw_from_i64(0)); } struct epoll_event *events = (struct epoll_event*)calloc((size_t)max_events, sizeof(struct epoll_event)); if (events == NULL) { fprintf(stderr, "Ironwall allocation failed in sys_epoll_pwait\n"); abort(); } int ready_count = epoll_pwait((int)iw_as_i64(raw_epoll_fd), events, (int)max_events, (int)iw_as_i64(raw_timeout_ms), NULL); if (ready_count < 0) { free(events); iw_syscall_abort("sys_epoll_pwait"); } iw_value_t result = iw_make_epoll_event_array(events, (int64_t)ready_count, "sys_epoll_pwait"); free(events); return result; }
static inline iw_value_t iw_builtin_sys_eventfd_create(iw_value_t raw_flags) { int fd = eventfd(0, (int)iw_as_i64(raw_flags)); if (fd < 0) { iw_syscall_abort("sys_eventfd_create"); } return iw_from_i64((int64_t)fd); }
static inline iw_value_t iw_builtin_sys_eventfd_write(iw_value_t raw_fd, iw_value_t raw_value) { uint64_t counter = (uint64_t)iw_as_i64(raw_value); ssize_t count = write((int)iw_as_i64(raw_fd), &counter, sizeof(counter)); if (count < 0) { iw_syscall_abort("sys_eventfd_write"); } if ((size_t)count != sizeof(counter)) { fprintf(stderr, "Ironwall short write in sys_eventfd_write: %lld\n", (long long)count); abort(); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_eventfd_read(iw_value_t raw_fd) { uint64_t counter = 0ULL; ssize_t count = read((int)iw_as_i64(raw_fd), &counter, sizeof(counter)); if (count < 0) { iw_syscall_abort("sys_eventfd_read"); } if ((size_t)count != sizeof(counter)) { fprintf(stderr, "Ironwall short read in sys_eventfd_read: %lld\n", (long long)count); abort(); } return iw_from_i64((int64_t)counter); }
static inline struct timespec iw_timespec_from_millis(int64_t millis, const char *context) { struct timespec spec; if (millis < 0) { fprintf(stderr, "Ironwall %s millis must be non-negative: %lld\n", context, (long long)millis); abort(); } spec.tv_sec = (time_t)(millis / 1000); spec.tv_nsec = (long)((millis % 1000) * 1000000LL); return spec; }
static inline iw_value_t iw_builtin_sys_timerfd_create_monotonic(iw_value_t raw_flags) { int fd = timerfd_create(CLOCK_MONOTONIC, (int)iw_as_i64(raw_flags)); if (fd < 0) { iw_syscall_abort("sys_timerfd_create_monotonic"); } return iw_from_i64((int64_t)fd); }
static inline iw_value_t iw_builtin_sys_timerfd_settime_oneshot_ms(iw_value_t raw_fd, iw_value_t raw_timeout_ms) { struct itimerspec spec; memset(&spec, 0, sizeof(spec)); spec.it_value = iw_timespec_from_millis(iw_as_i64(raw_timeout_ms), "sys_timerfd_settime_oneshot_ms"); if (timerfd_settime((int)iw_as_i64(raw_fd), 0, &spec, NULL) < 0) { iw_syscall_abort("sys_timerfd_settime_oneshot_ms"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_timerfd_settime_interval_ms(iw_value_t raw_fd, iw_value_t raw_initial_ms, iw_value_t raw_interval_ms) { struct itimerspec spec; memset(&spec, 0, sizeof(spec)); spec.it_value = iw_timespec_from_millis(iw_as_i64(raw_initial_ms), "sys_timerfd_settime_interval_ms initial_ms"); spec.it_interval = iw_timespec_from_millis(iw_as_i64(raw_interval_ms), "sys_timerfd_settime_interval_ms interval_ms"); if (timerfd_settime((int)iw_as_i64(raw_fd), 0, &spec, NULL) < 0) { iw_syscall_abort("sys_timerfd_settime_interval_ms"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_timerfd_read_expirations(iw_value_t raw_fd) { uint64_t expirations = 0ULL; ssize_t count = read((int)iw_as_i64(raw_fd), &expirations, sizeof(expirations)); if (count < 0) { iw_syscall_abort("sys_timerfd_read_expirations"); } if ((size_t)count != sizeof(expirations)) { fprintf(stderr, "Ironwall short read in sys_timerfd_read_expirations: %lld\n", (long long)count); abort(); } return iw_from_i64((int64_t)expirations); }
static inline iw_value_t iw_builtin_sys_signalfd_create_block(iw_value_t raw_signals, iw_value_t raw_flags) { iw_array_value_t *signals = iw_array_expect(raw_signals, "sys_signalfd_create_block signals"); sigset_t mask; if (sigemptyset(&mask) != 0) { iw_syscall_abort("sys_signalfd_create_block sigemptyset"); } for (int64_t index = 0; index < signals->length; index += 1) { if (sigaddset(&mask, (int)iw_as_i64(signals->items[index])) != 0) { iw_syscall_abort("sys_signalfd_create_block sigaddset"); } } if (sigprocmask(SIG_BLOCK, &mask, NULL) != 0) { iw_syscall_abort("sys_signalfd_create_block sigprocmask"); } int fd = signalfd(-1, &mask, (int)iw_as_i64(raw_flags)); if (fd < 0) { iw_syscall_abort("sys_signalfd_create_block"); } return iw_from_i64((int64_t)fd); }
static inline iw_value_t iw_builtin_sys_signalfd_read(iw_value_t raw_fd) { struct signalfd_siginfo info; memset(&info, 0, sizeof(info)); ssize_t count = read((int)iw_as_i64(raw_fd), &info, sizeof(info)); if (count < 0) { iw_syscall_abort("sys_signalfd_read"); } if ((size_t)count != sizeof(info)) { fprintf(stderr, "Ironwall short read in sys_signalfd_read: %lld\n", (long long)count); abort(); } return iw_make_signalfd_info_array((int64_t)info.ssi_signo, (int64_t)info.ssi_pid, (int64_t)info.ssi_uid, (int64_t)info.ssi_status, "sys_signalfd_read"); }
static inline void iw_prepare_pollfds(iw_value_t raw_fds, iw_value_t raw_events, struct pollfd **out_pollfds, int16_t **out_events, nfds_t *out_count, const char *context) { iw_array_value_t *fds = iw_array_expect(raw_fds, context); iw_array_value_t *events = iw_array_expect(raw_events, context); if (fds->length != events->length) { fprintf(stderr, "Ironwall %s requires matching fd/event array lengths: %lld vs %lld\n", context, (long long)fds->length, (long long)events->length); abort(); } nfds_t count = (nfds_t)fds->length; struct pollfd *pollfds = count == 0u ? NULL : (struct pollfd*)calloc(count, sizeof(struct pollfd)); int16_t *requested_events = count == 0u ? NULL : (int16_t*)calloc(count, sizeof(int16_t)); if (count != 0u && (pollfds == NULL || requested_events == NULL)) { free(pollfds); free(requested_events); fprintf(stderr, "Ironwall allocation failed in %s\n", context); abort(); } for (int64_t index = 0; index < fds->length; index += 1) { requested_events[index] = (int16_t)iw_as_i64(events->items[index]); pollfds[index].fd = (int)iw_as_i64(fds->items[index]); pollfds[index].events = requested_events[index]; pollfds[index].revents = 0; } *out_pollfds = pollfds; *out_events = requested_events; *out_count = count; }
static inline iw_value_t iw_finish_poll(iw_value_t raw_fds, iw_value_t raw_events, struct pollfd *pollfds, int16_t *requested_events, nfds_t count, const char *context) { (void)raw_fds; (void)raw_events; iw_value_t result = iw_make_poll_event_array(pollfds, requested_events, count, context); free(pollfds); free(requested_events); return result; }
static inline iw_value_t iw_builtin_sys_poll(iw_value_t raw_fds, iw_value_t raw_events, iw_value_t raw_timeout_ms) { struct pollfd *pollfds = NULL; int16_t *requested_events = NULL; nfds_t count = 0u; iw_prepare_pollfds(raw_fds, raw_events, &pollfds, &requested_events, &count, "sys_poll"); int ready_count = poll(pollfds, count, (int)iw_as_i64(raw_timeout_ms)); if (ready_count < 0) { free(pollfds); free(requested_events); iw_syscall_abort("sys_poll"); } return iw_finish_poll(raw_fds, raw_events, pollfds, requested_events, count, "sys_poll"); }
static inline iw_value_t iw_builtin_sys_ppoll(iw_value_t raw_fds, iw_value_t raw_events, iw_value_t raw_timeout_ms) { struct pollfd *pollfds = NULL; int16_t *requested_events = NULL; nfds_t count = 0u; iw_prepare_pollfds(raw_fds, raw_events, &pollfds, &requested_events, &count, "sys_ppoll"); int64_t timeout_ms = iw_as_i64(raw_timeout_ms); struct timespec timeout_spec; struct timespec *timeout_ptr = NULL; if (timeout_ms >= 0) { timeout_spec = iw_timespec_from_millis(timeout_ms, "sys_ppoll"); timeout_ptr = &timeout_spec; } int ready_count = ppoll(pollfds, count, timeout_ptr, NULL); if (ready_count < 0) { free(pollfds); free(requested_events); iw_syscall_abort("sys_ppoll"); } return iw_finish_poll(raw_fds, raw_events, pollfds, requested_events, count, "sys_ppoll"); }
static inline iw_value_t iw_builtin_sys_platform_name(void) { return iw_text_copy_bytes("linux", 5u, "sys_platform_name"); }
static inline iw_value_t iw_builtin_sys_process_argc(void) { size_t length = 0u; char *buffer = iw_load_proc_cmdline(&length, "sys_process_argc"); int64_t count = 0; size_t index = 0u; while (index < length) { size_t start = index; while (index < length && buffer[index] != '\0') { index += 1u; } if (index > start) { count += 1; } if (index < length) { index += 1u; } } free(buffer); return iw_from_i64(count); }
static inline iw_value_t iw_builtin_sys_process_argv_s3(iw_value_t raw_index) { int64_t wanted = iw_as_i64(raw_index); size_t length = 0u; char *buffer; size_t index = 0u; int64_t current = 0; if (wanted < 0) { iw_syscall_abort_message("sys_process_argv_s3", "argv index must be non-negative"); } buffer = iw_load_proc_cmdline(&length, "sys_process_argv_s3"); while (index < length) { size_t start = index; while (index < length && buffer[index] != '\0') { index += 1u; } if (index > start) { if (current == wanted) { iw_value_t result = iw_text_copy_bytes(buffer + start, index - start, "sys_process_argv_s3"); free(buffer); return result; } current += 1; } if (index < length) { index += 1u; } } free(buffer); iw_syscall_abort_message("sys_process_argv_s3", "argv index out of range"); return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_env_get_s3(iw_value_t raw_name) { iw_text_value_t *name = iw_text_expect(raw_name, "sys_env_get_s3 name"); const char *value = getenv(name->data); return value == NULL ? iw_text_copy_bytes("", 0u, "sys_env_get_s3") : iw_text_copy_bytes(value, strlen(value), "sys_env_get_s3"); }
static inline iw_value_t iw_builtin_sys_env_set_s3(iw_value_t raw_name, iw_value_t raw_value) { iw_text_value_t *name = iw_text_expect(raw_name, "sys_env_set_s3 name"); iw_text_value_t *value = iw_text_expect(raw_value, "sys_env_set_s3 value"); if (setenv(name->data, value->data, 1) != 0) { iw_syscall_abort("sys_env_set_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_env_unset_s3(iw_value_t raw_name) { iw_text_value_t *name = iw_text_expect(raw_name, "sys_env_unset_s3 name"); if (unsetenv(name->data) != 0) { iw_syscall_abort("sys_env_unset_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_path_getcwd_s3(void) { char *cwd = getcwd(NULL, 0); if (cwd == NULL) { iw_syscall_abort("sys_path_getcwd_s3"); } iw_value_t result = iw_text_copy_bytes(cwd, strlen(cwd), "sys_path_getcwd_s3"); free(cwd); return result; }
static inline iw_value_t iw_builtin_sys_path_chdir_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_chdir_s3 path"); if (chdir(path->data) < 0) { iw_syscall_abort("sys_path_chdir_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_path_exists_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_exists_s3 path"); struct stat stat_value; return iw_from_i64(stat(path->data, &stat_value) == 0 ? 1 : 0); }
static inline iw_value_t iw_builtin_sys_path_is_file_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_is_file_s3 path"); struct stat stat_value; if (stat(path->data, &stat_value) != 0) { return iw_from_i64(0); } return iw_from_i64(S_ISREG(stat_value.st_mode) ? 1 : 0); }
static inline iw_value_t iw_builtin_sys_path_is_dir_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_is_dir_s3 path"); struct stat stat_value; if (stat(path->data, &stat_value) != 0) { return iw_from_i64(0); } return iw_from_i64(S_ISDIR(stat_value.st_mode) ? 1 : 0); }
static inline iw_value_t iw_builtin_sys_path_mkdir_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_mkdir_s3 path"); if (mkdir(path->data, 0777) < 0) { iw_syscall_abort("sys_path_mkdir_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_path_rmdir_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_rmdir_s3 path"); if (rmdir(path->data) < 0) { iw_syscall_abort("sys_path_rmdir_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_path_unlink_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_unlink_s3 path"); if (unlink(path->data) < 0) { iw_syscall_abort("sys_path_unlink_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_path_rename_s3(iw_value_t raw_source_path, iw_value_t raw_target_path) { iw_text_value_t *source_path = iw_text_expect(raw_source_path, "sys_path_rename_s3 source path"); iw_text_value_t *target_path = iw_text_expect(raw_target_path, "sys_path_rename_s3 target path"); if (rename(source_path->data, target_path->data) != 0) { iw_syscall_abort("sys_path_rename_s3"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_path_stat_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_path_stat_s3 path"); struct stat stat_value; if (stat(path->data, &stat_value) != 0) { iw_syscall_abort("sys_path_stat_s3"); } return iw_make_i5_stat_array((int64_t)stat_value.st_dev, (int64_t)stat_value.st_ino, (int64_t)stat_value.st_mode, (int64_t)stat_value.st_nlink, (int64_t)stat_value.st_uid, (int64_t)stat_value.st_gid, (int64_t)stat_value.st_rdev, (int64_t)stat_value.st_size, (int64_t)stat_value.st_blksize, (int64_t)stat_value.st_blocks, (int64_t)stat_value.st_atime, (int64_t)stat_value.st_mtime, (int64_t)stat_value.st_ctime, "sys_path_stat_s3"); }
static inline iw_value_t iw_builtin_sys_dir_open_s3(iw_value_t raw_path) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_dir_open_s3 path"); DIR *dir = opendir(path->data); if (dir == NULL) { iw_syscall_abort("sys_dir_open_s3"); } return iw_from_i64((int64_t)(intptr_t)dir); }
static inline iw_value_t iw_builtin_sys_dir_read_s3(iw_value_t raw_dir_handle) { DIR *dir = (DIR*)(intptr_t)iw_as_i64(raw_dir_handle); struct dirent *entry; if (dir == NULL) { iw_syscall_abort_message("sys_dir_read_s3", "invalid directory handle"); } for (;;) { errno = 0; entry = readdir(dir); if (entry == NULL) { if (errno != 0) { iw_syscall_abort("sys_dir_read_s3"); } return iw_text_copy_bytes("", 0u, "sys_dir_read_s3"); } if (strcmp(entry->d_name, ".") != 0 && strcmp(entry->d_name, "..") != 0) { return iw_text_copy_bytes(entry->d_name, strlen(entry->d_name), "sys_dir_read_s3"); } } }
static inline iw_value_t iw_builtin_sys_dir_close(iw_value_t raw_dir_handle) { DIR *dir = (DIR*)(intptr_t)iw_as_i64(raw_dir_handle); if (dir == NULL) { iw_syscall_abort_message("sys_dir_close", "invalid directory handle"); } if (closedir(dir) != 0) { iw_syscall_abort("sys_dir_close"); } return iw_from_i64(0); }
static inline long iw_child_fd_close_limit(void) { long limit = sysconf(_SC_OPEN_MAX); if (limit < 0) { return 1024; } return limit; }
static inline void iw_child_close_non_stdio_fds(void) { DIR *dir = opendir("/proc/self/fd"); if (dir != NULL) { int dir_fd = dirfd(dir); struct dirent *entry; while ((entry = readdir(dir)) != NULL) { char *end = NULL; long fd = strtol(entry->d_name, &end, 10); if (end != entry->d_name && *end == '\0' && fd > 2 && fd != dir_fd) { (void)close((int)fd); } } closedir(dir); return; } long limit = iw_child_fd_close_limit(); if (limit > 1024) { limit = 1024; } for (int fd = 3; fd < limit; fd += 1) { (void)close(fd); } }
static inline iw_value_t iw_builtin_sys_process_spawn_common(iw_value_t raw_path, iw_value_t raw_argv, iw_value_t raw_envp, int use_stdio, int child_stdin_fd, int child_stdout_fd, int child_stderr_fd, const char *context) { iw_text_value_t *path = iw_text_expect(raw_path, context); char **argv = iw_text_array_to_exec_argv(raw_path, raw_argv, context); char **envp = iw_text_array_to_c_strings(raw_envp, context); pid_t pid = fork(); if (pid < 0) { free(argv); free(envp); iw_syscall_abort(context); } if (pid == 0) { if (use_stdio) { if (dup2(child_stdin_fd, STDIN_FILENO) < 0 || dup2(child_stdout_fd, STDOUT_FILENO) < 0 || dup2(child_stderr_fd, STDERR_FILENO) < 0) { iw_syscall_abort(context); } } iw_child_close_non_stdio_fds(); execve(path->data, argv, envp); iw_syscall_abort(context); } free(argv); free(envp); return iw_make_i5_process_array((int64_t)pid, context); }
static inline iw_value_t iw_builtin_sys_process_spawn_s3(iw_value_t raw_path, iw_value_t raw_argv, iw_value_t raw_envp) { return iw_builtin_sys_process_spawn_common(raw_path, raw_argv, raw_envp, 0, -1, -1, -1, "sys_process_spawn_s3"); }
static inline iw_value_t iw_builtin_sys_process_spawn_stdio_s3(iw_value_t raw_path, iw_value_t raw_argv, iw_value_t raw_envp, iw_value_t raw_stdin_fd, iw_value_t raw_stdout_fd, iw_value_t raw_stderr_fd) { return iw_builtin_sys_process_spawn_common(raw_path, raw_argv, raw_envp, 1, (int)iw_as_i64(raw_stdin_fd), (int)iw_as_i64(raw_stdout_fd), (int)iw_as_i64(raw_stderr_fd), "sys_process_spawn_stdio_s3"); }
static inline iw_value_t iw_builtin_sys_process_getpid(void) { return iw_from_i64((int64_t)getpid()); }
static inline iw_value_t iw_builtin_sys_process_fork(void) { pid_t pid = fork(); if (pid < 0) { iw_syscall_abort("sys_process_fork"); } return iw_from_i64((int64_t)pid); }
static inline iw_value_t iw_builtin_sys_process_execve_s3(iw_value_t raw_path, iw_value_t raw_argv, iw_value_t raw_envp) { iw_text_value_t *path = iw_text_expect(raw_path, "sys_process_execve_s3 path"); char **argv = iw_text_array_to_c_strings(raw_argv, "sys_process_execve_s3 argv"); char **envp = iw_text_array_to_c_strings(raw_envp, "sys_process_execve_s3 envp"); execve(path->data, argv, envp); free(argv); free(envp); iw_syscall_abort("sys_process_execve_s3"); return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_process_wait4(iw_value_t raw_pid) { int status = 0; if (waitpid((pid_t)iw_as_i64(raw_pid), &status, 0) < 0) { iw_syscall_abort("sys_process_wait4"); } return iw_from_i64((int64_t)status); }
static inline iw_value_t iw_builtin_sys_process_wait(iw_value_t raw_process_handle) { int status = 0; pid_t pid = (pid_t)iw_as_i64(raw_process_handle); if (waitpid(pid, &status, 0) < 0) { iw_syscall_abort("sys_process_wait"); } if (WIFEXITED(status)) { return iw_from_i64((int64_t)WEXITSTATUS(status)); } if (WIFSIGNALED(status)) { return iw_from_i64((int64_t)(128 + WTERMSIG(status))); } return iw_from_i64((int64_t)status); }
static inline iw_value_t iw_builtin_sys_process_kill(iw_value_t raw_process_handle) { if (kill((pid_t)iw_as_i64(raw_process_handle), SIGKILL) != 0) { iw_syscall_abort("sys_process_kill"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_process_exit(iw_value_t raw_code) { _exit((int)iw_as_i64(raw_code)); return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_process_exit_group(iw_value_t raw_code) { syscall(SYS_exit_group, (long)iw_as_i64(raw_code)); _exit((int)iw_as_i64(raw_code)); return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_time_unix_ms(void) { struct timespec spec; if (clock_gettime(CLOCK_REALTIME, &spec) != 0) { iw_syscall_abort("sys_time_unix_ms"); } return iw_from_i64(((int64_t)spec.tv_sec * 1000LL) + ((int64_t)spec.tv_nsec / 1000000LL)); }
static inline iw_value_t iw_builtin_sys_time_monotonic_ms(void) { struct timespec spec; if (clock_gettime(CLOCK_MONOTONIC, &spec) != 0) { iw_syscall_abort("sys_time_monotonic_ms"); } return iw_from_i64(((int64_t)spec.tv_sec * 1000LL) + ((int64_t)spec.tv_nsec / 1000000LL)); }
static inline iw_value_t iw_builtin_sys_thread_gettid(void) { long result = syscall(SYS_gettid); if (result < 0) { iw_syscall_abort("sys_thread_gettid"); } return iw_from_i64((int64_t)result); }
static inline iw_value_t iw_builtin_sys_thread_tgkill(iw_value_t raw_tgid, iw_value_t raw_tid, iw_value_t raw_signal) { long result = syscall(SYS_tgkill, (long)iw_as_i64(raw_tgid), (long)iw_as_i64(raw_tid), (long)iw_as_i64(raw_signal)); if (result < 0) { iw_syscall_abort("sys_thread_tgkill"); } return iw_from_i64(0); }
static inline iw_value_t iw_builtin_sys_thread_yield(void) { long result = syscall(SYS_sched_yield); if (result < 0) { iw_syscall_abort("sys_thread_yield"); } return iw_from_i64(0); }
