#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=1

usage() {
  cat <<'USAGE'
Usage: ./clean-qmake-builds.sh [--apply]

Recursively clean qmake-generated build files under this astvis-qt tree.

Default mode is dry-run. Pass --apply to delete the listed files/directories.
USAGE
}

for arg in "$@"; do
  case "$arg" in
    --apply)
      DRY_RUN=0
      ;;
    -n|--dry-run)
      DRY_RUN=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      usage >&2
      exit 2
      ;;
  esac
done

declare -a TARGETS=()

add_target() {
  local path="$1"
  TARGETS+=("$path")
}

has_project_file() {
  local dir="$1"
  compgen -G "$dir/*.pro" >/dev/null
}

collect_qmake_state_files() {
  while IFS= read -r -d '' path; do
    add_target "$path"
  done < <(
    find "$ROOT_DIR" -type f \
      \( -name '.qmake.stash' -o -name '.qmake.cache' -o -name '.qmake.super' \) \
      -print0
  )
}

collect_qmake_makefiles() {
  while IFS= read -r -d '' path; do
    if grep -Iq 'Generated by qmake' "$path"; then
      add_target "$path"
    fi
  done < <(
    find "$ROOT_DIR" -type f \
      \( -name 'Makefile' -o -name 'Makefile.*' \) \
      -print0
  )
}

collect_qmake_build_dirs() {
  while IFS= read -r -d '' path; do
    local parent
    parent="$(dirname "$path")"
    if has_project_file "$parent"; then
      add_target "$path"
    fi
  done < <(
    find "$ROOT_DIR" -type d \
      \( -name debug -o -name release \) \
      -print0
  )
}

collect_project_generated_files() {
  while IFS= read -r -d '' project_file; do
    local project_dir
    project_dir="$(dirname "$project_file")"
    while IFS= read -r -d '' path; do
      add_target "$path"
    done < <(
      find "$project_dir" -maxdepth 1 -type f \
        \( -name '*.o' \
        -o -name '*.obj' \
        -o -name '*.res' \
        -o -name '*.pch' \
        -o -name 'moc_*.cpp' \
        -o -name 'moc_*.h' \
        -o -name 'qrc_*.cpp' \
        -o -name 'ui_*.h' \
        -o -name '*.moc' \
        -o -name 'object_script.*' \) \
        -print0
    )
  done < <(find "$ROOT_DIR" -type f -name '*.pro' -print0)
}

collect_qmake_state_files
collect_qmake_makefiles
collect_qmake_build_dirs
collect_project_generated_files

if ((${#TARGETS[@]} == 0)); then
  echo "No qmake-generated build files found under $ROOT_DIR"
  exit 0
fi

if ((DRY_RUN)); then
  echo "Dry run: qmake-generated build files that would be removed:"
else
  echo "Removing qmake-generated build files:"
fi

for path in "${TARGETS[@]}"; do
  printf '  %s\n' "${path#$ROOT_DIR/}"
done

if ((DRY_RUN)); then
  echo
  echo "Run with --apply to delete these paths."
  exit 0
fi

for path in "${TARGETS[@]}"; do
  rm -rf -- "$path"
done

echo "Cleaned ${#TARGETS[@]} path(s)."
