import type {
    WindowsCBackendSourcePass1Sections,
    WindowsCBackendX64SupportPass1Sections
} from "./Backend-Windows-C-Pass-1-CollectSections";

const WINDOWS_C_BACKEND_DRIVER_MARKER = "/* IW_WINDOWS_C_BACKEND_DRIVER */";

const WINDOWS_C_BACKEND_INCLUDE_LINES: readonly string[] = [
    "#ifndef _CRT_SECURE_NO_WARNINGS",
    "#define _CRT_SECURE_NO_WARNINGS",
    "#endif",
    "#ifndef _WIN32_WINNT",
    "#define _WIN32_WINNT 0x0600",
    "#endif",
    "#ifndef WIN32_LEAN_AND_MEAN",
    "#define WIN32_LEAN_AND_MEAN",
    "#endif",
    "#include <stdint.h>",
    "#include <stdlib.h>",
    "#include <stdio.h>",
    "#include <stddef.h>",
    "#include <errno.h>",
    "#include <math.h>",
    "#include <stdarg.h>",
    "#include <string.h>",
    "#include <time.h>",
    "#include <limits.h>",
    "#include <wchar.h>",
    "#include <fcntl.h>",
    "#include <io.h>",
    "#include <direct.h>",
    "#include <process.h>",
    "#include <sys/types.h>",
    "#include <sys/stat.h>",
    "#include <winsock2.h>",
    "#include <ws2tcpip.h>",
    "#include <windows.h>",
    "#pragma comment(lib, \"shell32.lib\")",
    "__declspec(dllimport) LPWSTR *WINAPI CommandLineToArgvW(LPCWSTR lpCmdLine, int *pNumArgs);",
    "#ifndef _Thread_local",
    "#define _Thread_local __declspec(thread)",
    "#endif",
    "#ifndef IW_INTERNAL_ABI",
    "#define IW_INTERNAL_ABI __attribute__((sysv_abi))",
    "#endif",
    "#ifndef IW_HOST_ABI",
    "#define IW_HOST_ABI",
    "#endif",
    "typedef intptr_t pid_t;",
    "typedef struct iw_win32_thread_t { HANDLE handle; unsigned id; } iw_win32_thread_t;",
    "typedef DWORD iw_win32_tls_key_t;",
    "typedef SRWLOCK iw_win32_mutex_t;",
    "typedef CONDITION_VARIABLE iw_win32_condition_t;",
    "typedef INIT_ONCE iw_win32_once_t;",
    "typedef struct iw_win32_thread_start_context_t { unsigned (__stdcall *start_routine)(void *); void *arg; } iw_win32_thread_start_context_t;",
    "#define IW_WIN32_MUTEX_INITIALIZER SRWLOCK_INIT",
    "#define IW_WIN32_CONDITION_INITIALIZER CONDITION_VARIABLE_INIT",
    "#define IW_WIN32_ONCE_INIT INIT_ONCE_STATIC_INIT",
    "static BOOL CALLBACK iw_win32_once_callback(PINIT_ONCE iw_once, PVOID iw_parameter, PVOID *iw_context) {",
    "    (void)iw_once;",
    "    (void)iw_context;",
    "    ((void (*)(void))iw_parameter)();",
    "    return TRUE;",
    "}",
    "static inline int iw_win32_once(iw_win32_once_t *once_control, void (*init_routine)(void)) {",
    "    return InitOnceExecuteOnce(once_control, iw_win32_once_callback, (PVOID)init_routine, NULL) ? 0 : EINVAL;",
    "}",
    "static unsigned __stdcall iw_win32_thread_start_trampoline(void *raw_context) {",
    "    iw_win32_thread_start_context_t *context = (iw_win32_thread_start_context_t*)raw_context;",
    "    unsigned (__stdcall *start_routine)(void *) = context->start_routine;",
    "    void *arg = context->arg;",
    "    free(context);",
    "    return start_routine(arg);",
    "}",
    "static inline int iw_win32_thread_create(iw_win32_thread_t *thread, unsigned (__stdcall *start_routine)(void *), void *arg) {",
    "    iw_win32_thread_start_context_t *context;",
    "    uintptr_t handle_value;",
    "    if (thread == NULL || start_routine == NULL) {",
    "        return EINVAL;",
    "    }",
    "    context = (iw_win32_thread_start_context_t*)malloc(sizeof(iw_win32_thread_start_context_t));",
    "    if (context == NULL) {",
    "        return ENOMEM;",
    "    }",
    "    context->start_routine = start_routine;",
    "    context->arg = arg;",
    "    handle_value = _beginthreadex(NULL, 0u, iw_win32_thread_start_trampoline, context, 0u, &thread->id);",
    "    if (handle_value == 0u) {",
    "        free(context);",
    "        return errno != 0 ? errno : EAGAIN;",
    "    }",
    "    thread->handle = (HANDLE)handle_value;",
    "    return 0;",
    "}",
    "static inline int iw_win32_thread_join(iw_win32_thread_t thread) {",
    "    DWORD wait_result;",
    "    if (thread.handle == NULL) {",
    "        return EINVAL;",
    "    }",
    "    wait_result = WaitForSingleObject(thread.handle, INFINITE);",
    "    return wait_result == WAIT_OBJECT_0 ? 0 : EINVAL;",
    "}",
    "static inline int iw_win32_thread_close(iw_win32_thread_t thread) {",
    "    if (thread.handle == NULL) {",
    "        return EINVAL;",
    "    }",
    "    return CloseHandle(thread.handle) ? 0 : EINVAL;",
    "}",
    "static inline void iw_win32_thread_exit(unsigned exit_code) {",
    "    _endthreadex(exit_code);",
    "}",
    "static inline iw_win32_thread_t iw_win32_thread_current(void) {",
    "    iw_win32_thread_t thread;",
    "    thread.handle = NULL;",
    "    thread.id = GetCurrentThreadId();",
    "    return thread;",
    "}",
    "static inline int iw_win32_thread_equal(iw_win32_thread_t left, iw_win32_thread_t right) {",
    "    return left.id == right.id;",
    "}",
    "static inline int iw_win32_mutex_init(iw_win32_mutex_t *mutex) {",
    "    InitializeSRWLock(mutex);",
    "    return 0;",
    "}",
    "static inline int iw_win32_mutex_lock(iw_win32_mutex_t *mutex) {",
    "    AcquireSRWLockExclusive(mutex);",
    "    return 0;",
    "}",
    "static inline int iw_win32_mutex_unlock(iw_win32_mutex_t *mutex) {",
    "    ReleaseSRWLockExclusive(mutex);",
    "    return 0;",
    "}",
    "static inline int iw_win32_mutex_trylock(iw_win32_mutex_t *mutex) {",
    "    return TryAcquireSRWLockExclusive(mutex) ? 0 : EBUSY;",
    "}",
    "static inline int iw_win32_mutex_destroy(iw_win32_mutex_t *mutex) {",
    "    (void)mutex;",
    "    return 0;",
    "}",
    "static inline int iw_win32_condition_init(iw_win32_condition_t *cond) {",
    "    InitializeConditionVariable(cond);",
    "    return 0;",
    "}",
    "static inline int iw_win32_condition_wait(iw_win32_condition_t *cond, iw_win32_mutex_t *mutex) {",
    "    return SleepConditionVariableSRW(cond, mutex, INFINITE, 0) ? 0 : EINVAL;",
    "}",
    "static inline int iw_win32_condition_timed_wait_ms(iw_win32_condition_t *cond, iw_win32_mutex_t *mutex, DWORD timeout_ms) {",
    "    if (SleepConditionVariableSRW(cond, mutex, timeout_ms, 0)) {",
    "        return 0;",
    "    }",
    "    return GetLastError() == ERROR_TIMEOUT ? ETIMEDOUT : EINVAL;",
    "}",
    "static inline int iw_win32_condition_signal(iw_win32_condition_t *cond) {",
    "    WakeConditionVariable(cond);",
    "    return 0;",
    "}",
    "static inline int iw_win32_condition_broadcast(iw_win32_condition_t *cond) {",
    "    WakeAllConditionVariable(cond);",
    "    return 0;",
    "}",
    "static inline int iw_win32_condition_destroy(iw_win32_condition_t *cond) {",
    "    (void)cond;",
    "    return 0;",
    "}",
    "static inline int iw_win32_tls_alloc(iw_win32_tls_key_t *key) {",
    "    DWORD tls_index;",
    "    if (key == NULL) {",
    "        return EINVAL;",
    "    }",
    "    tls_index = TlsAlloc();",
    "    if (tls_index == TLS_OUT_OF_INDEXES) {",
    "        return EAGAIN;",
    "    }",
    "    *key = tls_index;",
    "    return 0;",
    "}",
    "static inline int iw_win32_tls_set(iw_win32_tls_key_t key, const void *value) {",
    "    return TlsSetValue(key, (LPVOID)value) ? 0 : EINVAL;",
    "}",
    "static inline void *iw_win32_tls_get(iw_win32_tls_key_t key) {",
    "    return TlsGetValue(key);",
    "}",
    "static inline int iw_win32_tls_delete(iw_win32_tls_key_t key) {",
    "    return TlsFree(key) ? 0 : EINVAL;",
    "}",
    "typedef iw_win32_thread_t pthread_t;",
    "typedef iw_win32_mutex_t pthread_mutex_t;",
    "typedef iw_win32_condition_t pthread_cond_t;",
    "typedef iw_win32_once_t pthread_once_t;",
    "#define PTHREAD_MUTEX_INITIALIZER IW_WIN32_MUTEX_INITIALIZER",
    "#define PTHREAD_COND_INITIALIZER IW_WIN32_CONDITION_INITIALIZER",
    "#define PTHREAD_ONCE_INIT IW_WIN32_ONCE_INIT",
    "static inline pthread_t pthread_self(void) { return iw_win32_thread_current(); }",
    "static inline int pthread_equal(pthread_t left, pthread_t right) { return iw_win32_thread_equal(left, right); }",
    "static inline int pthread_once(pthread_once_t *once_control, void (*init_routine)(void)) { return iw_win32_once(once_control, init_routine); }",
    "static inline int pthread_mutex_init(pthread_mutex_t *mutex, const void *attrs) { (void)attrs; return iw_win32_mutex_init(mutex); }",
    "static inline int pthread_mutex_lock(pthread_mutex_t *mutex) { return iw_win32_mutex_lock(mutex); }",
    "static inline int pthread_mutex_unlock(pthread_mutex_t *mutex) { return iw_win32_mutex_unlock(mutex); }",
    "static inline int pthread_mutex_trylock(pthread_mutex_t *mutex) { return iw_win32_mutex_trylock(mutex); }",
    "static inline int pthread_mutex_destroy(pthread_mutex_t *mutex) { return iw_win32_mutex_destroy(mutex); }",
    "static inline int pthread_cond_init(pthread_cond_t *cond, const void *attrs) { (void)attrs; return iw_win32_condition_init(cond); }",
    "static inline int pthread_cond_wait(pthread_cond_t *cond, pthread_mutex_t *mutex) { return iw_win32_condition_wait(cond, mutex); }",
    "static inline int pthread_cond_signal(pthread_cond_t *cond) { return iw_win32_condition_signal(cond); }",
    "static inline int pthread_cond_broadcast(pthread_cond_t *cond) { return iw_win32_condition_broadcast(cond); }",
    "static inline int pthread_cond_destroy(pthread_cond_t *cond) { return iw_win32_condition_destroy(cond); }",
    "#ifndef SYS_gettid",
    "#define SYS_gettid 186",
    "#endif",
    "static inline intptr_t iw_windows_syscall(long number) {",
    "    if (number == SYS_gettid) {",
    "        return (intptr_t)GetCurrentThreadId();",
    "    }",
    "    errno = ENOSYS;",
    "    return (intptr_t)-1;",
    "}",
    "#define syscall(number) iw_windows_syscall(number)"
];

export function performWindowsCBackendSourcePass2AssembleRuntimeAndDriverSource(
    sections: WindowsCBackendSourcePass1Sections
): string {
    return [
        ...WINDOWS_C_BACKEND_INCLUDE_LINES,
        "",
        sections.builtinHelpers,
        "",
        sections.classRuntime,
        "",
        sections.gcFrameRuntime,
        "",
        sections.runtimeDescriptors,
        "",
        sections.gcMetadataRuntime,
        "",
        sections.globalRuntime,
        "",
        sections.gcRuntimeSupport,
        "",
        sections.prototypes,
        "",
        sections.stdSysFfiRuntime,
        "",
        sections.declaredCHeapHostHelperRuntime,
        "",
        sections.exportedIwFunctionRuntime,
        "",
        sections.hostArgvRuntime,
        "",
        sections.hostEntryWrapper,
        "",
        sections.closureRuntime,
        "",
        sections.textRuntime,
        "",
        sections.normalizedExtraSupportSource,
        "",
        sections.emittedFunctions,
        "",
        WINDOWS_C_BACKEND_DRIVER_MARKER,
        "",
        "int main(int argc, char **argv) {",
        "    {",
        "        int iw_stack_anchor_local = 0;",
        "        uintptr_t iw_stack_anchor = (uintptr_t)&iw_stack_anchor_local;",
        "        iw_gc_init_runtime(iw_stack_anchor);",
        "    }",
        `    ${sections.driverResultType} result = __iw_host_entry_main(argc, argv);`,
        "    return (int)iw_as_i64(result);",
        "}"
    ].join("\n");
}

export function performWindowsCBackendX64SupportPass2AssembleSource(
    sections: WindowsCBackendX64SupportPass1Sections
): string {
    return [
        ...WINDOWS_C_BACKEND_INCLUDE_LINES,
        "",
        sections.builtinHelpers,
        "",
        sections.classRuntime,
        "",
        sections.gcFrameRuntime,
        "",
        sections.runtimeDescriptors,
        "",
        sections.gcMetadataRuntime,
        "",
        sections.globalRuntime,
        "",
        sections.compiledPrototypes,
        "",
        sections.stdSysFfiRuntime,
        "",
        sections.declaredCHeapHostHelperRuntime,
        "",
        sections.exportedIwFunctionRuntime,
        "",
        sections.gcRuntimeSupport,
        "",
        sections.hostArgvRuntime,
        "",
        sections.hostEntryWrapper,
        "",
        sections.closureRuntime,
        "",
        sections.textRuntime,
        "",
        sections.boxedNumberRuntime,
        "",
        sections.directFunctionRuntime,
        "",
        sections.normalizedExtraSupportSource,
        "",
        sections.supportWrappers,
        "",
        sections.omitRuntimeInit
            ? ""
            : [
                "void __iw_x64_init_runtime(void) {",
                "    int iw_stack_anchor_local = 0;",
                "    uintptr_t iw_stack_anchor = (uintptr_t)&iw_stack_anchor_local;",
                "    iw_gc_init_runtime(iw_stack_anchor);",
                "}"
            ].join("\n")
    ].join("\n");
}