import type {
    LinuxCBackendSourcePass1Sections,
    LinuxCBackendX64SupportPass1Sections
} from "./Backend-Linux-C-Pass-1-CollectSections";

const LINUX_C_BACKEND_INCLUDE_LINES: readonly string[] = [
    "#define _GNU_SOURCE",
    "#define _POSIX_C_SOURCE 200809L",
    "#include <stdint.h>",
    "#include <stdlib.h>",
    "#include <stdio.h>",
    "#include <stddef.h>",
    "#include <errno.h>",
    "#include <math.h>",
    "#include <string.h>",
    "#include <unistd.h>",
    "#include <signal.h>",
    "#include <time.h>",
    "#include <pthread.h>",
    "#include <fcntl.h>",
    "#include <poll.h>",
    "#include <sys/sendfile.h>",
    "#include <sys/signalfd.h>",
    "#include <sys/socket.h>",
    "#include <sys/uio.h>",
    "#include <netinet/in.h>",
    "#include <netinet/tcp.h>",
    "#include <sys/epoll.h>",
    "#include <sys/eventfd.h>",
    "#include <sys/timerfd.h>",
    "#include <sys/stat.h>",
    "#include <sys/resource.h>",
    "#include <sys/types.h>",
    "#include <sys/wait.h>",
    "#include <sys/syscall.h>",
    "#ifndef IW_INTERNAL_ABI",
    "#define IW_INTERNAL_ABI __attribute__((sysv_abi))",
    "#endif",
    "#ifndef IW_HOST_ABI",
    "#define IW_HOST_ABI",
    "#endif"
];

export function performLinuxCBackendSourcePass2AssembleRuntimeAndDriverSource(
    sections: LinuxCBackendSourcePass1Sections
): string {
    return [
        ...LINUX_C_BACKEND_INCLUDE_LINES,
        "",
        sections.builtinHelpers,
        "",
        sections.classRuntime,
        "",
        sections.gcFrameRuntime,
        "",
        sections.runtimeDescriptors,
        "",
        sections.gcMetadataRuntime,
        "",
        sections.globalRuntime,
        "",
        sections.gcRuntimeSupport,
        "",
        sections.prototypes,
        "",
        sections.stdSysFfiRuntime,
        "",
        sections.declaredCHeapHostHelperRuntime,
        "",
        sections.exportedIwFunctionRuntime,
        "",
        sections.hostArgvRuntime,
        "",
        sections.hostEntryWrapper,
        "",
        sections.closureRuntime,
        "",
        sections.textRuntime,
        "",
        sections.normalizedExtraSupportSource,
        "",
        sections.emittedFunctions,
        "",
        "static void iw_raise_stack_limit(void) {",
        "    struct rlimit limit;",
        "    if (getrlimit(RLIMIT_STACK, &limit) != 0) {",
        "        return;",
        "    }",
        "    if (limit.rlim_cur == limit.rlim_max) {",
        "        return;",
        "    }",
        "    limit.rlim_cur = limit.rlim_max;",
        "    (void)setrlimit(RLIMIT_STACK, &limit);",
        "}",
        "",
        "int main(int argc, char **argv) {",
        "    iw_raise_stack_limit();",
        "    {",
        "        int iw_stack_anchor_local = 0;",
        "        uintptr_t iw_stack_anchor = (uintptr_t)&iw_stack_anchor_local;",
        "        iw_gc_init_runtime(iw_stack_anchor);",
        "    }",
        `    ${sections.driverResultType} result = __iw_host_entry_main(argc, argv);`,
        "    return (int)iw_as_i64(result);",
        "}"
    ].join("\n");
}

export function performLinuxCBackendX64SupportPass2AssembleSource(
    sections: LinuxCBackendX64SupportPass1Sections
): string {
    return [
        ...LINUX_C_BACKEND_INCLUDE_LINES,
        "",
        sections.builtinHelpers,
        "",
        sections.classRuntime,
        "",
        sections.gcFrameRuntime,
        "",
        sections.runtimeDescriptors,
        "",
        sections.gcMetadataRuntime,
        "",
        sections.globalRuntime,
        "",
        sections.compiledPrototypes,
        "",
        sections.stdSysFfiRuntime,
        "",
        sections.declaredCHeapHostHelperRuntime,
        "",
        sections.exportedIwFunctionRuntime,
        "",
        sections.gcRuntimeSupport,
        "",
        sections.hostArgvRuntime,
        "",
        sections.hostEntryWrapper,
        "",
        sections.closureRuntime,
        "",
        sections.textRuntime,
        "",
        sections.boxedNumberRuntime,
        "",
        sections.directFunctionRuntime,
        "",
        sections.normalizedExtraSupportSource,
        "",
        sections.supportWrappers,
        "",
        sections.omitRuntimeInit
            ? ""
            : [
                "void __iw_x64_init_runtime(void) {",
                "    int iw_stack_anchor_local = 0;",
                "    uintptr_t iw_stack_anchor = (uintptr_t)&iw_stack_anchor_local;",
                "    iw_gc_init_runtime(iw_stack_anchor);",
                "}"
            ].join("\n")
    ].join("\n");
}